apiVersion: v1
kind: Pod
metadata:
  name: ngd-kafka-zookeeper
  namespace: default
  labels:
    name: ngd-kafka-zookeeper
spec:
  hostNetwork: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: In
                values:
                  - "true"
  restartPolicy: Always
  containers:
    - name: ngd-kafka-zookeeper
      image: 10.1.1.1:27443/ngd-kafka:0.0.1
      imagePullPolicy: Always
      env:
        - name: SERVICE
          value: ZOOKEEPER
      ports:
        - containerPort: 2181
