FROM ubuntu:20.04

ENV DEBIAN_FRONTEND="noninteractive"
ENV DEBUG="True"

RUN apt update \
    && ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
    && apt install build-essential clang \
        openjdk-8-jdk openjdk-8-jre maven -yq

EXPOSE 2181
EXPOSE 9092

WORKDIR /app

COPY kafka_2.13-3.0.0 .

COPY src .

CMD ["/app/start_server.development.sh"]
